server:
  port: 0 # 랜덤 포트

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##hyeni
    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka # Discovery Eureka 설정 주가

greeting:
  message: Welcome to the Simple E-comerce.

logging:
  level:
    com.example.user_service: DEBUG

token:
  expiration_time: 86400000 # 하루짜리 토큰 생성
  secret : mySuperSecureKeyThatIsDefinitelyAtLeastSixtyFourBytesLong!!!123456